export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"

export const FETCH_KATAS_BEGIN = "FETCH_KATAS_BEGIN"
export const FETCH_KATAS_FAILURE = "FETCH_KATAS_BEGIN"
export const FETCH_KATAS_SUCCESS = "FETCH_KATAS_SUCCESS"

export const FETCH_KATAS_TO_REVIEW_SUCCESS =
  "FETCH_KATAS_BEGIN_TO_REVIEW_SUCCESS"

export const FETCH_DECKS_BEGIN = "FETCH_DECKS_BEGIN"
export const FETCH_DECKS_FAILURE = "FETCH_DECKS_BEGIN"
export const FETCH_DECKS_SUCCESS = "FETCH_DECKS_SUCCESS"

export const FETCH_DECKS_TO_REVIEW_SUCCESS =
  "FETCH_DECKS_BEGIN_TO_REVIEW_SUCCESS"

export const RUN_CODE_BEGIN = "RUN_CODE_BEGIN"
export const RUN_CODE_SUCCESS = "RUN_CODE_SUCCESS"
export const RUN_CODE_FAILURE = "RUN_CODE_FAILURE"

export const ENABLE_VIM = "ENABLE_VIM"
export const DISABLE_VIM = "DISABLE_VIM"

export const ON_STRENGTHEN = "ON_STRENGTHEN"
export const ON_NEXT_KATA = "ON_NEXT_KATA"

export const CLEAN_DECK_REDUCER = "CLEAN_DECK_REDUCER"
